### ISSUE TITLE
Roadmap to release

### ISSUE THREAD

**Issue by SoNiceElijah** [Ejoktank/scheduler-bot#2]
Few steps to make this bot better and ready for production

- [ ] Review dialog lines. Put text to constants.
- [ ] Review dialog line titles: give appropriate names & move to constants
- [ ] Write better text, add some emoji 
- [ ] Test this peace of shift
- [ ] Review functionality and think about features that must be in release version

**Comment by Ejoktank** [comment]
It'll also be really exciting if we could program amount of particular message
In case if I have some very important task to do so it needs to be reminded several times, e.g. every 2 hours the whole day or every day in the morning the whole week
